fn: allow setting CUDA stream
GridTools/gridtools pull request #1712
Opened 2022-04-29 14:03 UTC by havogt

2022-04-29 14:05 UTC, havogt commented on tests/regression/fn/fn_tridiagonal_solve.cpp
> +            cudaStream_t s;
remove

2022-04-29 14:05 UTC, havogt commented on include/gridtools/common/cuda_util.hpp
> +// #ifdef GT_CUDACC
cleanup

2022-05-05 11:17 UTC, havogt commented
launch jenkins

2022-05-05 11:17 UTC, havogt commented
launch perftest

2022-05-06 13:55 UTC, fthaler requested changes
Looks good. I just propose to be a bit more consistent with passing the backend by const ref where possible to avoid unnecessary copies in case we might have backends with heavier run-time payload in the future.

2022-05-06 13:55 UTC, fthaler commented on include/gridtools/fn/run.hpp
> +            Backend backend, StageSpecs, MakeIterator const &make_iterator, Domain const &domain, Sids &&sids) {
```suggestion
            Backend const &backend, StageSpecs, MakeIterator const &make_iterator, Domain const &domain, Sids &&sids) {
```

2022-05-06 13:55 UTC, fthaler commented on include/gridtools/fn/run.hpp
> +        void run_column_stages(Backend backend,
```suggestion
        void run_column_stages(Backend const &backend,
```

2022-05-06 13:55 UTC, fthaler commented on include/gridtools/fn/cartesian.hpp
> +        auto make_backend(Backend b, cartesian_domain<Sizes, Offsets> const &d) {
```suggestion
        auto make_backend(Backend const &b, cartesian_domain<Sizes, Offsets> const &d) {
```

2022-05-06 13:55 UTC, fthaler commented on include/gridtools/fn/executor.hpp
> +            Backend backend, Sizes const &sizes, Offsets const &offsets, MakeIterator const &make_iterator) {
```suggestion
            Backend const &backend, Sizes const &sizes, Offsets const &offsets, MakeIterator const &make_iterator) {
```

2022-05-06 13:55 UTC, fthaler commented on include/gridtools/fn/unstructured.hpp
> +        auto make_backend(Backend b, domain_with_offsets<Tables, Sizes, Offsets> const &d) {
```suggestion
        auto make_backend(Backend const &b, domain_with_offsets<Tables, Sizes, Offsets> const &d) {
```

2022-05-12 11:07 UTC, havogt commented on include/gridtools/fn/backend/gpu.hpp
> +            gpu<BlockSizes> g, Sizes const &sizes, StencilStage, MakeIterator make_iterator, Composite &&composite) {
```suggestion
            gpu<BlockSizes>const &g, Sizes const &sizes, StencilStage, MakeIterator make_iterator, Composite &&composite) {
```

2022-05-12 11:07 UTC, havogt commented on include/gridtools/fn/backend/gpu.hpp
> +        void apply_column_stage(gpu<BlockSizes> g,
```suggestion
        void apply_column_stage(gpu<BlockSizes> const &g,
```

2022-05-12 11:08 UTC, havogt commented
launch jenkins

2022-05-12 11:08 UTC, havogt commented
launch perftest

2022-05-13 05:16 UTC, merged