Fix perftests CMake target being empty: https://github.com/GridTools/gridtools/issues/1551
GridTools/gridtools pull request #1724
Opened 2022-07-26 15:00 UTC by petiaccja

2022-07-26 15:01 UTC, gridtoolsjenkins commented
Hi there, this is jenkins continuous integration... 
Do you want me to verify this patch?

2022-07-27 07:08 UTC, havogt requested changes
Just a minor thing: let's put it in the current build dir, i.e. in <build>/tests/regression.

2022-07-27 07:08 UTC, havogt commented on tests/regression/CMakeLists.txt
> +     "${CMAKE_BINARY_DIR}/perftests_dummy.cpp"
```suggestion
     "${CMAKE_CURRENT_BINARY_DIR}/perftests_dummy.cpp"
```

2022-07-27 07:08 UTC, havogt commented on tests/regression/CMakeLists.txt
> +target_sources(perftests PRIVATE "${CMAKE_BINARY_DIR}/perftests_dummy.cpp")
```suggestion
target_sources(perftests PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/perftests_dummy.cpp")
```

2022-07-27 08:54 UTC, havogt approved these changes
Thanks. Looks good (as good as CMake allows).

2022-07-28 09:17 UTC, petiaccja commented
launch jenkins

2022-08-09 15:14 UTC, havogt commented
launch jenkins

2022-08-10 16:51 UTC, petiaccja commented
launch jenkins

2022-08-10 18:32 UTC, petiaccja commented
launch jenkins

2022-08-11 15:40 UTC, petiaccja commented
launch jenkins

2022-08-11 16:44 UTC, petiaccja commented
launch jenkins

2022-08-16 13:21 UTC, petiaccja commented
launch perftest

2022-08-16 14:28 UTC, merged