Pybind11: ignore mismatch on integer representation for boolean type
GridTools/gridtools pull request #1780
Opened 2024-06-04 10:31 UTC by edopao

In pybind11 bindings, allow both `int8_t` and `uint8_t` representations for boolean type. The mismatch on the signess of the integer type, in this case, should not lead to an error.

2024-06-04 10:35 UTC, gridtoolsjenkins commented
Hi there, this is jenkins continuous integration... 
Do you want me to verify this patch?

2024-06-04 10:36 UTC, edopao commented
launch jenkins

2024-06-04 10:36 UTC, edopao commented
launch perftests

2024-06-10 12:49 UTC, fthaler requested changes
Looks good to me, but tests are missing. Please just add one to `tests/regression/py_bindings/` that tests the previously failing cases.

2024-06-11 08:34 UTC, closed without merging