Explicitly Use __ldg on Pointer Derefs
GridTools/gridtools pull request #1800
Opened 2024-07-24 10:27 UTC by fthaler

Used the `__ldg` intrinsic on (scalar) pointer derefs in SID neighbor tables and derefs within the fn cartesian and unstructured backends.

2024-07-24 10:28 UTC, fthaler commented
launch perftest

2024-07-24 10:28 UTC, fthaler commented
launch jenkins

2024-07-24 10:30 UTC, gridtoolsjenkins commented
Hi there, this is jenkins continuous integration... 
Do you want me to verify this patch?

2024-08-02 14:47 UTC, havogt requested changes

2024-08-02 14:47 UTC, havogt commented on include/gridtools/fn/cartesian.hpp
> +#if defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 350
We only support cuda >= 11.0, therefore anyway no support for < 350

2024-08-02 14:47 UTC, havogt commented on include/gridtools/fn/cartesian.hpp
> +#endif
what about introducing a function like
`deref_as_const`?

2024-08-14 09:22 UTC, fthaler commented
Closed in favor of #1802

2024-08-14 09:22 UTC, closed without merging