Fixes for HIP detection for recent ROCm and CMake
GridTools/gridtools pull request #1804
Opened 2024-09-19 09:23 UTC by havogt

2024-09-24 09:20 UTC, havogt commented
launch jenkins

2024-09-24 10:42 UTC, havogt commented
launch jenkins

2024-09-25 07:06 UTC, fthaler requested changes

2024-09-25 07:06 UTC, fthaler commented on cmake/public/gridtools_setup_targets.cmake
> +            if(GT_CUDA_TYPE STREQUAL HIPCC-AMDGPU)
```suggestion
            elseif(GT_CUDA_TYPE STREQUAL HIPCC-AMDGPU)
```

2024-09-25 07:06 UTC, fthaler commented on include/gridtools/common/cuda_util.hpp
> +                        on_error(err, "cudaFree", "", "", 0);
Why not `GT_CUDA_CHECK`?
```suggestion
                    GT_CUDA_CHECK(cudaFree(const_cast<std::remove_cv_t<T> *>(ptr)));
```

2024-09-25 07:47 UTC, havogt commented on CMakeLists.txt
> +# TODO(havogt): rename variable to GT_CLANG_MODE in backwards compatible way
I would leave that TODO for now.

2024-09-25 07:53 UTC, havogt commented
launch jenkins

2024-09-25 09:26 UTC, fthaler approved these changes

2024-09-25 11:11 UTC, havogt commented
launch jenkins

2024-09-26 06:55 UTC, merged